### ISSUE TITLE
Auto Travis build

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/markedmondson.me-hugo#2]
Run the deploy script upon a github push

**Comment by MarkEdmondson1234** [comment]
- Make sure to add both build and website repo to travis permissions
- Dont rely on r packages
- Submodules needs a hack to be used on travis
- Deploy script doesn't  see Rscript and needs github auth

So far:

```yml
language: r
cache: packages
# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    ## non R-package installation
    - Rscript -e 'install.packages("devtools")'
    - Rscript -e 'devtools::install_github("rstudio/blogdown")'
install: 
 - Rscript -e 'blogdown::install_hugo()'
 - Rscript -e 'blogdown::install_theme("digitalcraftsman/hugo-icarus-theme")'
script: ./deploy.sh
after_success: echo "Done"
```
